// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiaEFtfBfr7sxaXlKBqslM82__LKeC1Bo',
    appId: '1:909928306188:web:801ec77fec409f86938029',
    messagingSenderId: '909928306188',
    projectId: 'thachinchord',
    authDomain: 'thachinchord.firebaseapp.com',
    storageBucket: 'thachinchord.firebasestorage.app',
    measurementId: 'G-7F9B2DHFGE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_-hsp-tUqUjcbvsRwS1Y1hK_HxV9rm_k',
    appId: '1:909928306188:android:5dc6b49429c63c3b938029',
    messagingSenderId: '909928306188',
    projectId: 'thachinchord',
    storageBucket: 'thachinchord.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLmzN-a_0hn0-ImLjE9Ncj3P4yVeOi3CM',
    appId: '1:909928306188:ios:fce7294261870ae6938029',
    messagingSenderId: '909928306188',
    projectId: 'thachinchord',
    storageBucket: 'thachinchord.firebasestorage.app',
    iosBundleId: 'com.example.thachinchord',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLmzN-a_0hn0-ImLjE9Ncj3P4yVeOi3CM',
    appId: '1:909928306188:ios:fce7294261870ae6938029',
    messagingSenderId: '909928306188',
    projectId: 'thachinchord',
    storageBucket: 'thachinchord.firebasestorage.app',
    iosBundleId: 'com.example.thachinchord',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAiaEFtfBfr7sxaXlKBqslM82__LKeC1Bo',
    appId: '1:909928306188:web:2924b3775d1054cc938029',
    messagingSenderId: '909928306188',
    projectId: 'thachinchord',
    authDomain: 'thachinchord.firebaseapp.com',
    storageBucket: 'thachinchord.firebasestorage.app',
    measurementId: 'G-XGYJSQGK6V',
  );
}
